### ISSUE TITLE
Customization of UI and use case

### ISSUE THREAD

**Issue by Sander-Kornev** [alan-ai/alan-sdk-ios#3]
I have a few questions:

1. Is it possible to customize AlanButton look? For example, use my own icon.
2. Is it possible to show Dialogue UI in a separate screen so that it would look like a chat UI with questions/commands from the user and answers from the Alan SDK? It seems that Alan's responses can be retrieved in `onCommand handler` . What about user's requests? 

Thanks

**Comment by andreyryabov** [comment]
Hi Sander,

1. [https://alan.app/docs/usage/button/customization/#changing-the-alan-button-visual-style](https://alan.app/docs/usage/button/customization/#changing-the-alan-button-visual-style)
2. Someone will followup with you on this.

**Comment by okolyachko** [comment]
Hi Sander,

To capture what the user says and Alan's response, you can use the onEvent handler: https://alan.app/docs/client-api/methods/event-handler/. You seem to be looking for the parsed and text events. 

If you need any help with this, please contact us at support@alan.app.
